\hypertarget{classcppparsec_1_1parse__failed}{}\doxysection{cppparsec\+::parse\+\_\+failed Class Reference}
\label{classcppparsec_1_1parse__failed}\index{cppparsec::parse\_failed@{cppparsec::parse\_failed}}


{\ttfamily \#include $<$error.\+h$>$}

Inheritance diagram for cppparsec\+::parse\+\_\+failed\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classcppparsec_1_1parse__failed}
\end{center}
\end{figure}
\doxysubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classcppparsec_1_1parse__failed_a04bb7c47357de17a4b1636f0b1ff9d4b}\label{classcppparsec_1_1parse__failed_a04bb7c47357de17a4b1636f0b1ff9d4b}} 
{\bfseries parse\+\_\+failed} (const std\+::string \&msg)
\item 
\mbox{\Hypertarget{classcppparsec_1_1parse__failed_aed534372d07f94c95dc1ab7d2881fb86}\label{classcppparsec_1_1parse__failed_aed534372d07f94c95dc1ab7d2881fb86}} 
const char $\ast$ {\bfseries what} () const noexcept override
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
the top level exception that will only be thrown by the {\ttfamily get} function of {\ttfamily reply}. This exception throws all \mbox{\hyperlink{classcppparsec_1_1parser__error}{parser\+\_\+error}} messages as formatted string. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
include/error.\+h\end{DoxyCompactItemize}
